# Generated by Django 6.0.6 on 2026-07-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_unique_nonempty_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(choices=[('default', 'Default'), ('lazarus', 'Lazarus')], default='default', max_length=40),
        ),
    ]
