# Generated by Django 6.0.6 on 2026-07-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(choices=[('default', 'Default'), ('axel', 'Axel'), ('eleina', 'Eleina'), ('kyojuro', 'Kyojuro'), ('kyoya', 'Kyoya'), ('levi', 'Levi'), ('mikasa', 'Mikasa'), ('rui', 'Rui'), ('ryuga', 'Ryuga'), ('sanemi', 'Sanemi')], default='default', max_length=40),
        ),
    ]
